Homework02. Написание решателя Судоку
DamirZv/cs102 pull request #2
Opened 2020-10-26 20:43 UTC by DamirZv

## Premise
Для реализации решателя необходимо знать, что такое 

- Списки и списковые включения (https://dabeaz-course.github.io/practical-python/Notes/02_Working_with_data/06_List_comprehension.html)
- Множество set () (https://python-scripts.com/sets)
- Модуль Randome  и его функции ( https://pythonworld.ru/moduli/modul-random.html)
- Кортежи

2020-10-27 16:42 UTC, Dementiy requested changes
Вы какую работу сдаете? Первую?

![Снимок экрана 2020-10-27 в 19 42 16](https://user-images.githubusercontent.com/4396325/97333337-86251f80-188c-11eb-914a-54677fb134da.png)

2020-10-27 16:44 UTC, DamirZv commented
> Вы какую работу сдаете? Первую?
> 
>
> 
> ![Снимок экрана 2020-10-27 в 19 42 16](https://user-images.githubusercontent.com/4396325/97333337-86251f80-188c-11eb-914a-54677fb134da.png)
> 
> Здравствуйте, нет. Я случайно отправил review на первую. Следом отправил на вторую

2020-10-28 12:15 UTC, Dementiy requested changes
Ничего не изменилось, файлов от первой работы быть не должно:

![Снимок экрана 2020-10-28 в 15 15 19](https://user-images.githubusercontent.com/4396325/97434660-65160a80-1930-11eb-87d7-6fea7ef53c4b.png)

2020-10-30 17:29 UTC, Dementiy requested changes
Ничего не изменилось:

![Снимок экрана 2020-10-30 в 20 28 59](https://user-images.githubusercontent.com/4396325/97737803-8cb2d180-1aee-11eb-972d-77bc150ca98e.png)

Пожалуйста перед запросом на проверку посмотрите сами, удалили ли вы все ненужные файлы или нет. Тогда вы быстрее сдадите работу.

2020-11-02 16:43 UTC, Dementiy requested changes
1. Есть небольшое замечание
2. Настройте github actions, в пул реквесте возле работы должна стоять зеленая галочка.

2020-11-02 16:43 UTC, Dementiy commented on homework02/sudoku.py
> +        return []
У функции задача сгенерировать Судоку, а не вернуть пустой список.

2020-11-03 20:16 UTC, Dementiy approved these changes

2020-11-03 20:32 UTC, merged